### ISSUE TITLE
Changing number of available CUs

### ISSUE THREAD

**Issue by pfotouhi** [ROCm/ROCm#1012]
I'm studying scaling of a variety of compute workloads, and I was wondering if there is a way to adjust the number of CUs?

I came across a [similar discussion](https://github.com/RadeonOpenCompute/ROC-smi/issues/5) where use of "hsa_amd_queue_cu_set_mask()" was suggested. Since this requires changing the applications source code, are there any other alternative approaches that can achieve the same without modifying the source code?

**Comment by pfotouhi** [comment]
More on this one, can "hsa_amd_queue_cu_set_mask()" used somewhere inside rocprof to disbale CUs while profiling?

**Comment by ROCmSupport** [comment]
Thanks @pfotouhi for reaching out.
Request you to share an update like whether you are still looking for the same query.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @pfotouhi 
Feel free to close this issue, if you do not have any open query.
Thank you.

**Comment by jlgreathouse** [comment]
I'm sorry for the long delay in responding to this. As of ROCm 4.5, we have a mechanism that should help you do what you want. The environment variable HSA_CU_MASK (with syntax described [here](https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/rocm-5.6.0/src/core/util/flag.cpp#L105)) will allow you to set the CU mask on all queues created within a process without needing to modify any code.

Please note that not all CU masks are legal on all devices. For instance, on gfx10+ devices where two CUs can be combined together into a WGP (for kernels running in WGP mode), [it is not legal to disable only a single CU in a WGP](https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/rocm-5.6.0/src/core/runtime/amd_aql_queue.cpp#L1130). You may want to [read this paper](https://www.cs.unc.edu/~otternes/papers/rtsj2022.pdf) where a research group explores how setting some CU masks (such as enabling one CU on an SE and all CUs on another SE) can lead to corner-case situations that do not perform as you would expect.

I'm relatively confident (though I haven't tested it at this time) that setting this environment variable will also cause the CU mask to be set on queues being profiled, because this sets the mask on the lowest-level of our queue creation, the ROCr runtime. This is different than the [ROC_GLOBAL_CU_MASK environment variable](https://github.com/ROCm-Developer-Tools/ROCclr/blob/rocm-5.6.0/utils/flags.hpp#L258), which will only set the CU mask on queues created by the HIP and OpenCL language runtimes.

All of these environment variables are for ROCm software only, and will not work for graphics workloads (such as Mesa). There is a driver-level mechanism to disable CUs ([the amdgpu modparm disable_cu](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/master/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c#L517)), but this will apply to all GPUs in your system. In addition, setting this incorrectly (e.g., disabling all CUs in an SE, which is legal for CU masking but not for this modparm) can lead to a non-working GPU. This modparm is not recommended for production usage.

**Comment by keryell** [comment]
There is quite a lot of interesting information here!
@saadrahim it would be nice to have this described in a synthetic way in the official documentation.

**Comment by saadrahim** [comment]
@jlgreathouse unless you object by closing this, I am reopening this include this content directly in the repository.

**Comment by nartmada** [comment]
Internal ticket has been created to track of the progress of this task.

**Comment by neon60** [comment]
We can close this issue, because the page is added:

https://github.com/ROCm/ROCm/blob/develop/docs/how-to/setting-cus.rst

@saadrahim I will close this tomorrow, if I do not get any comments.
