### ISSUE TITLE
Performance drop between 5.3 and 5.4 with the RX6700s on resnet50

### ISSUE THREAD

**Issue by MatPoliquin** [ROCm/ROCm#1877]
After installing rocm 5.4 on a fresh install of Ubuntu 22.10 I get a performance drop compared to rocm 5.3 on the same OS/hardware

Steps to reproduce:
```
pip3 install tensorflow-rocm
git clone https://github.com/tensorflow/benchmarks.git
cd benchmarks/scripts/tf_cnn_benchmarks
export HSA_OVERRIDE_GFX_VERSION=10.3.0
python3 tf_cnn_benchmarks.py --num_gpus=1 --batch_size=32 --model=resnet50
```
Results:

- with 5.3 : **total images/sec: 97.40**
- with 5.4 : **total images/sec: 80.03**

Specs:

- Ubuntu 22.10 - Kernel 5.19.X
- Asus g14 2022 laptop
- RX 6700s  8GB
- R7 6800HS 16GB DDR5

**Comment by alexschroeter** [comment]
I have also seen regression in performance from 5.3.3 to 5.4.0. We suspected regression in FFT because it is our main compute part but I believe resnet is not using FFT and maybe we are looking at a more general issue (we haven't found the time to investigate where the time is lost). We are running Ubuntu 22.04 LTS, Kernel 5.15.0-56, on https://www.supermicro.com/en/Aplus/system/4U/4124/AS-4124GS-TNR.cfm with two AMD EPYC 7452 32-Core Processor,

**Comment by nartmada** [comment]
Hi @MatPoliquin and @alexschroeter, can you please try latest ROCm 6.0.2 and check if your performance issue has been resolved?  Thanks.

**Comment by alexschroeter** [comment]
Sorry, but I don't have access to the hard- and software anymore. Maybe OP still has access to his setup.

**Comment by nartmada** [comment]
Closing the ticket as no response from @MatPoliquin.  Please re-open if this is still an issue with latest ROCm 6.0.2.  Thanks.
