### ISSUE TITLE
Did rumored Fiji / Fury / nano / gfx803 support in ROCm 5.5 Release happen?

### ISSUE THREAD

**Issue by RhynarAI** [ROCm/ROCm#2101]
Since "the internet reported" about Fury support in the upcoming release, I was getting my hopes up for a re-use of my Fury X... I can´t spot any mentioning of it in the release notes in V 5.5

Could the ROCm team please clarify? Older posts state "dropped support" for gfx803/Fury/Fiji

**Comment by saadrahim** [comment]
I do apologize, the rumours are not true. Fiji support has been dropped. There is no plan to add it back.

**Comment by xuhuisheng** [comment]
@RhynarAI 
If you are special interesting with gfx803 - fiji, polaris, you can try my patch : <https://github.com/xuhuisheng/rocm-gfx803>

Som kind people said they can run Stable diffusion on gfx803 sucessfully. But I hadn't confirm it by myself.

And, gfx900 - vega64 is just on the AMDGPU_TARGETS list, I don't know why AMD didn't include gfx900 on the supporting list. It should run without any patch. I sugguest you give a try.

**Comment by cgmb** [comment]
This was a bit of a miscommunication. The support table had a column that described which parts of the stack the table was describing. It was listed as "full" because the information in the columns to the right applied to the entire stack.

The gfx803 architecture is still available in the binaries that AMD provides for the ROCm math and communication libraries, although you need to set the environment variable `ROC_ENABLE_PRE_VEGA=1` to enable support in ROCclr. However, AMD stopped testing the gfx803 architecture with ROCm 3.5 and there are some known bugs (e.g., with certain operations in rocBLAS). Similarly, there has been no testing for gfx900 since ROCm 4.5. Trying to communicate this situation was one of the goals of the updated support table.

The ROCm librararies are still open to receiving patches that fix issues on these architectures, but stability is also quite important. We can't accept patches that fix some things and break other things. If you have a targeted fix for a problem on an unsupported architecture, you may want to ping me on the PR and I will try to help it along (as not all developers have easy access to unsupported hardware for testing those kinds of changes).

However, I would encourage you to work with one of the distros in maintaining support for these older architectures. I'm pretty involved with Debian and the primary maintainers of ROCm on that platform all have gfx803 GPUs available. They have also enabled ROC_ENABLE_PRE_VEGA by default so you don't have to set the environment variable. The one thing they don't have is very much free time. They're already very busy just trying to get ROCm packages into Debian at all, so I'm sure they would be happy if you want to help test packages on gfx803 and file bug reports. If you have a good patch, the turnaround time for a release of a new version of a distro package with a bugfix is likely to be much faster than a new ROCm release.

**Comment by RhynarAI** [comment]
Thank you to both of you for responding. SOrry for my late reply, got manged up at work :)
I´ll have to free up some time to fiddle a little more with it, seems it is possible to get the Furys running somehow - And while I love tampering with this kind of stuff (its a challenge) - AMD would really do itself a favour if they made "stuff like this simpler". In the meanwhile, I grabbed my 3060 , installed it and was ready to go with everything I wanted to get done/try out/etc... Same card for gaming, video editing, inference loads for video editing, etc... And it works - out of the box. No "use this patch, swap the kernel, stick to this distro"...

Meanwhile, the internet is still confused about which cards run and which don´t - since AMD is getting a little into the game, any community I watch that somehow needs compute power has picked up on the new AI API, Rocm releases, HIP Support in Blender and things like this... And in EVERY Discussion, no one has a clue what works and what not - and this fires back on AMD - while one should think that its "Good news" that AMD gets more involved -bad communication or "only nerds get it running" attidude leads to a situation, where the "good news" in discussions turns into: "now we know for sure - stick to Nvidia"... Before, no body was really sure if AMD could be used  - now they have 20 people in the discussion who all tried, failed and therefore switched to Nvidia.... Much worse situation, marketing-wise...

So sad.... I recently used a Fury in ONNX Inference - this oldie really packs a punch, still today..

**Comment by xuhuisheng** [comment]
BTW, I upload a patch for blender with gfx803, too.
Anybody who interested can take a try: <https://github.com/xuhuisheng/rocm-gfx803/blob/master/blender.md>

**Comment by RhynarAI** [comment]
Thanx for this. 

I see that  a lot is possible to get running when doing some patching here, fiddling there... Sadly, I don´t have the time to tamper with all of this - as a hobby "to get it going", its fine - but in a serious workflow environment, time is money... the time to get stuff running simply is not worth it - compared to NVIDIA, where even old maxwell cards simply work...

(this is mostly aimed at AMD, not your patch - I really do think AMD should change the taktiks about supporting older GPUs .... Although I do own a lot of AMD GPUs and don`t like the fact that for most creative workloads people simply buy Nvidia - I can totally understand the decisions.. )


I appreciate your patches - if I find time, I`ll dig into this - but it really is too much effort to get stuff running, the Fury will probably find the way to ebay before I find time to dig in...

**Comment by nartmada** [comment]
Hi @RhynarAI, sorry we are not able to help you much on this ticket.  Can we close the ticket?  Thanks.

**Comment by RhynarAI** [comment]
Thank you for catching up. 

It was too much work for me to get the Fury running. I did use it in DIRECT ML Workloads a few times, but eventually sold them and got a NVIDIA GPU - now I can run everything without much trouble and the speeds are much better...

Would have loved to stay with AMD..

**Comment by RhynarAI** [comment]
> Hi @RhynarAI, sorry we are not able to help you much on this ticket. Can we close the ticket? Thanks.

yes, the ticket can be closed. Thank you.
