### ISSUE TITLE
[OMP] hipcc won't define _OPENMP macro

### ISSUE THREAD

**Issue by dipietrantonio** [ROCm/ROCm#2186]
Dear developers, the `hipcc` compiler driver won't define the `_OPENMP` macro when the `-fopenmp` option is specified. The macro will be defined only when GPU offloading is requested. This can cause issues during the CMake configuration step when testing for OpenMP availability.

ROCm versions: 5.0.2, 5.4.3

How to reproduce:

```
$ cat test.cpp 
#ifndef _OPENMP
#error NO OPENMP defined
#endif

int main () {}
$ hipcc -fopenmp test.cpp 
test.cpp:2:2: error: NO OPENMP defined
#error NO OPENMP defined
 ^
1 error generated when compiling for gfx90a.
$ clang -fopenmp test.cpp 
$ # success 
$ hipcc -fopenmp -target x86_64-pc-linux-gnu -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx90a test.cpp 
$ # success
```
Is this the intended behaviour?

Thank you

**Comment by ppanchad-amd** [comment]
@dipietrantonio Apologies for the lack response.  Do you still need assistance with this ticket? Thanks!

**Comment by dipietrantonio** [comment]
Hi @ppanchad-amd,

the error is still present in rocm/5.7.3, I cannot test for later versions yet but I suspect it is still there. I believe this should be fixed as soon as possible.

**Comment by harkgill-amd** [comment]
Hi @dipietrantonio, this is the intended behaviour as OpenMP is not enabled for the GPU. A simple workaround for this issue is to guard the OpenMP code from entering the GPU compilation as shown below:

```
#ifndef __HIP_DEVICE_COMPILE__
#ifndef _OPENMP
#error NO OPENMP defined
#endif
#endif
```
This will prevent the `#ifndef _OPENMP #error NO OPENMP defined` assertation from throwing an error.

**Comment by dipietrantonio** [comment]
hi @harkgill-amd I will do some experimenting and will get back to you. I had issues because I was using OpenMP but for CPU parallelisation in other parts of the code. One can still use OpenMP together with HIP..

**Comment by harkgill-amd** [comment]
Hi @dipietrantonio, any updates on this?

**Comment by dipietrantonio** [comment]
Hi @harkgill-amd, thanks for your patience. I think there has been a misunderstanding.

I am currently working on a library that has a CPU and GPU implementation for every numerical algorithm. I want them to coexist together. I am using OpenMP for CPU parallelisation and HIP to offload to GPU. I am NOT using OpenMP offloading features.

This setup works, meaning that `hipcc` is happy to compile my OpenMP functions and HIP code in the same object file. And the code runs fine.

My problem is only with the `_OPENMP` macro. Because I give the option to the user whether to compile with OpenMP or not,  I would like the macro to be defined when I pass `-fopenmp`.  To recap, OpenMP CPU + HIP works fine, I just need `hipcc` to define the macro.

**Comment by zichguan-amd** [comment]
Hi @dipietrantonio, if all you need is to have `_OPENMP` defined, the compiler already does that. You can verify it with 
```
$ echo | hipcc -fopenmp -dM -E - | grep OPENMP
#define _OPENMP 202011
```
The error only happens during compilation because the compiler compiles the source code in separate passes for CPU and GPU, and openmp is not enabled for GPU, therefore it fails at the GPU pass. The previous suggestion guards the error exactly from it. You can use the macro for CPU at runtime with no problem.

**Comment by dipietrantonio** [comment]
Hi @zichguan-amd , @harkgill-amd thank you both for your explanation, considering the two passes now it makes sense to me.
