### ISSUE TITLE
AI Engine (AIE) and -ML (AIE-ML) support

### ISSUE THREAD

**Issue by EwoutH** [ROCm/ROCm#2247]
I would love to see ROCm platform's support for AMD's [AI Engine](https://www.xilinx.com/products/technology/ai-engine.html), part of the Versal ACAP architecture. Specifically, the two variants AIE and AIE-ML, found in chips like the AMD Ryzen 7x40HS and 7x40U series.

If ROCm already supports the AI Engine (both AIE and AIE-ML), then this is a request for documentation on it. If it doesn't, consider this a feature request to include such support.

**Comment by saadrahim** [comment]
ROCm does not support the AMD AI Engine. 

Is there a particular use case that you are making a feature request for? Please elaborate if possible.

**Comment by chaudhariatul** [comment]
Unified support with Raedon GPU, Xilinx FPGA available with AMD Ryzen 7x40HS and 7x40U series will improve the edge device solutions. This will be great value add.

**Comment by keryell** [comment]
I have been waiting for years to have a laptop myself with an AMD Ryzen 9 7940HS. :-)
But how do you imagine AIE support in ROCm? Something like HIP?
Each work-item in a GPU can access its global memory while on AIE you cannot without programming some DMA to transfer explicitly some memory chunks to get the performance.
So either the programming style is different from HIP (but can still be part of ROCm at large) or you need a serious auto-magic compiler.
But if you have some good ideas, you are welcome. :-)
Otherwise there is a research project making progress and you can look at the latest presentation of https://xilinx.github.io/mlir-aie/Presentations.html

**Comment by saadrahim** [comment]
Please see https://ryzenai.docs.amd.com/en/latest/
