### ISSUE TITLE
[Documentation] Explicit tensorflow wheel naming convention for installation

### ISSUE THREAD

**Issue by pierreantoineH** [ROCm/ROCm#2327]
The compatibility matrix between Tensorflow and ROCm is indicated in : 
https://rocm.docs.amd.com/en/latest/release/3rd_party_support_matrix.html

Nevertheless it might not be obvious that the wheel naming convention is TFversion.0.ROCmversion which might lead user to install Tensorflow wheel for not the right ROCm version.

On https://rocm.docs.amd.com/en/latest/how_to/tensorflow_install/tensorflow_install.html , it is indicated : 
For details on tensorflow-rocm wheels and ROCm version compatibility, see:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md
which is much more explicit but did not contain the latest compatibility matrix. (i.e ROCm 5.6 & Tensorflow 2.12)

**Comment by saadrahim** [comment]
@sunway513 can you help assign this issue?

**Comment by ppanchad-amd** [comment]
@pierreantoineH @saadrahim Internal ticket has been created to fix documentation. Thanks!

**Comment by harkgill-amd** [comment]
Hi @pierreantoineH, this issue is addressed in https://github.com/ROCm/rocm-install-on-linux/commit/ff56cdbc23f3e751e066587fd65e528763ee5465. Going forward, the naming convention for the wheels will follow the TF version (First wheel to follow this was `2.16.1`). A note has also been added in the documentation to highlight the `TFversion.ROCmversion` format for older wheels.
