### ISSUE TITLE
[Feature]: Installation steps for Debian 12

### ISSUE THREAD

**Issue by misaligar** [ROCm/ROCm#2802]
### Suggestion Description

Can you please provide instructions to get ROCm installed on Debian 12? I believe I can follow the Ubuntu instructions with some caveat. But it would be much better if you can include official step by step installation guide. Thanks!

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/index.html

### Operating System

Debian 12

### GPU

7900 XTX

**Comment by supersonictw** [comment]
Duplicated
https://github.com/ROCm/ROCm/issues/2646

**Comment by cgmb** [comment]
Hi @misaligar, AMD doesn't provide official support for ROCm on Debian, which is why there isn't an official installation guide for Bookworm. I know that some users on Debian install binaries into an Ubuntu container and copy them into `/opt/rocm` on their Debian installation, but I've never tried it myself. Ideally, there would be ROCm packages available in the `bookworm-backports` repo.

The Debian ROCm Team plans to prepare backports once they complete the update to ROCm 5.7 and the packaging of pytorch-rocm for Debian Trixie. If there are any particular packages that you need that are not yet packaged for Debian, please feel free to file an RFP on the Debian bug tracker.

And, of course, it never hurts to get involved yourself. There's a relatively small group of volunteers maintaining ROCm packages on Debian. A few more volunteers with the right skills and motivation could really speed up the process.

**Comment by misaligar** [comment]
Thank you!
