### ISSUE TITLE
[Issue]: .to("cuda") gets stuck on WSL2

### ISSUE THREAD

**Issue by Sidies** [ROCm/ROCm#3952]
### Problem Description

Hi,

I am running a WSL2 instance and followed these two guides to get torch installed and rocm installed:
https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-radeon.html
https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html

The installation process worked without issues but when loading models from huggingface it gets stuck on the "Loading checkpoint shards" step.

This only happens when i use .to("cuda")
So this works:
```python
model = AutoModelForCausalLM.from_pretrained("sciphi/triplex", trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained("sciphi/triplex", trust_remote_code=True)
``` 

But this does not work:
```python
model = AutoModelForCausalLM.from_pretrained("sciphi/triplex", trust_remote_code=True).to("cuda").eval()
tokenizer = AutoTokenizer.from_pretrained("sciphi/triplex", trust_remote_code=True)
``` 

### Operating System

Ubuntu 22.04.5 LTS (Jammy Jellyfish)"

### CPU

AMD Ryzen 9 5900X 12-Core Processor

### GPU

AMD Radeon RX 6800 XT

### ROCm Version

ROCm 6.1.0

**Comment by harkgill-amd** [comment]
Hi @Sidies, this issue is due to the RX 6800 XT not currently being supported for usage on WSL. It's expected that the 6800 XT will be detected in rocminfo but hang when utilizing the GPU in your program. Please refer to the [WSL Compatibility Matrix](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility/wsl/wsl_compatibility.html#gpu-support-matrix) for a list of supported GPUs.
