### ISSUE TITLE
[Documentation]: Installing Tensorflow with Rocm

### ISSUE THREAD

**Issue by ansamz** [ROCm/ROCm#3986]
### Description of errors

Attempting to follow the official instructions [here](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/tensorflow-install.html) on an Ubuntu 24.04 system with a rocm 6.2 and a 7900XTX.

My understanding is that the variables I need are:

* repo = `https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/`
* wheel-version = `2.14.1` or `2.15.1`  or `2.16.1`.

But when I attempt to install tensorflow from the given repository using these instructions I get a not found error:

```
$ pip install tensorflow-rocm==2.16.1 -f https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/ --upgrade
Looking in links: https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/
ERROR: Could not find a version that satisfies the requirement tensorflow-rocm==2.16.1 (from versions: none)
ERROR: No matching distribution found for tensorflow-rocm==2.16.1


# The same happens when I try 2.14.1 or 2.15.1 or 2.16
```

Unfortunately my understanding of `pip` is limited and I do not understand why it is unable to find the version that satisfies the requirements. Am I doing something obviously wrong or is there a problem with the documentation?

I was looking forward to using my 7900xtx for some machine learning work. In fact the promised rocm support was the reason I went with this card.

**Comment by harkgill-amd** [comment]
Hi @ansamz, it's likely that `pip` can't find the correct wheel due to a python version mismatch. The tensorflow-rocm 2.16.1 wheel is meant for use with Python 3.10, any other python version in the host environment will result in `pip` throwing an error. Could you please try the installation in a python3.10 virtual environment and let me know if this resolves your issue?

If this is the case, I'll look into getting the documentation updated to better notify users of this requirement.

**Comment by harkgill-amd** [comment]
Closing this issue out due to lack of reply. Feel free to leave a comment if you're still experiencing any issues and I'll re-open this issue. Thanks!
