### ISSUE TITLE
[Issue]: trying to run Ollama docker on WSL2 with 7900XTX but no "/dev/kfd" folder

### ISSUE THREAD

**Issue by Henry715** [ROCm/ROCm#4062]
### Problem Description

I can confirm that I have installed the ROCm and PyTorch on WSL correctly (according to the official document and this: https://github.com/ROCm/ROCm/issues/3563), as all post install checks are passed (rocminfo command works and pytorch retuen "True" for checking CUDA). but when I run "docker run -d --device /dev/kfd --device /dev/dri -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:rocm
", it says "ERROR:  /dev/kfd no such file or directory". 

However I have came across this issue: https://github.com/ROCm/ROCm/issues/3734, so I substitute "--device /dev/kfd" to "--device /dev/dxg", it still cannot recognize the GPU and run the model on CPU. But if I just installed the .exe from Ollama official website, that one does utilize the GPU. 

And I have also came across to this: https://github.com/ollama/ollama/issues/5275, which it basically says it is expected to have no directory called "/dev/kfd" by following the instructions, but I haven't try the poster's method for fear that the system would break. So is this a recognized issue and will be fixed in future or I am doing something wrong?  

P.S. I am sorry that I have deleted all the setups because it got me frustrated, but I will do this again and post the log of not finding the GPU here shortly after.

### Operating System

Ubuntu 22.04.5 LTS (WSL2) / Ubuntu 24.04.1 LTS (WSL2)

### CPU

Ryzen R7-7700X

### GPU

AMD Radeon 7900XTX

### ROCm Version

ROCm 6.2.3 / ROCm 6.1.3

**Comment by Henry715** [comment]
I will try to provide as much information as possible, so here is the results of step 1 in the official document:
![image](https://github.com/user-attachments/assets/f48b6f1b-f81e-42af-bad7-44d6f9453981)

**Comment by tcgu-amd** [comment]
Hi @Henry715, thanks for reaching out! Getting Ollama working in WSL docker is going to be a little bit complicated. 

First, please follow Option: B of [this guide](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html) to get docker with ROCm running on WSL. In addition to mapping /dev/dxg, the instruction also helps you to map a couple core ROCm libraries. 

However, this does not fully help with getting Ollama to run because it stills looks for kfd explicitly under the hood. Hence, You might want to follow [these instructions](https://github.com/ollama/ollama/issues/5275#issuecomment-2270886785) in order to override this behavior. 

Hope this helps. Please do not hesitate to reach out if you have any additional questions.

Cheers!

**Comment by Henry715** [comment]
> Hi @Henry715, thanks for reaching out! Getting Ollama working in WSL docker is going to be a little bit complicated.
> 
> First, please follow Option: B of [this guide](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html) to get docker with ROCm running on WSL. In addition to mapping /dev/dxg, the instructions also helps you map a couple core ROCm libraries.
> 
> However, this does not fully help with getting Ollama to run because it stills looks for kfd explicitly under the hood. Hence, You might want to follow [these instructions](https://github.com/ollama/ollama/issues/5275#issuecomment-2270886785) in order to override this behavior.
> 
> Since the modifications are mainly going to be focused on the Ollama code, I wouldn't be too worried about breaking anything in the system.
> 
> Hope this helps. Please do not hesitate to reach out if you have any additional questions.
> 
> Cheers!

Sure, I will definitely try those. If I installed the docker container with Pytorch, does that mean I should run Ollama in that Pytorch Docker container rather than using that Ollama:ROCm official docker image?

**Comment by evshiron** [comment]
> Sure, I will definitely try those. If I installed the docker container with Pytorch, does that mean I should run Ollama in that Pytorch Docker container rather than using that Ollama:ROCm official docker image?

First of all, Ollama doesn't depend on PyTorch. The error occurred because it expected the normal AMD driver to be installed, which in WSL is not.

ROCm (and CUDA) in WSL use custom tricky libraries (a.k.a. `libdxcore.so`) to redirect instructions to the host, which is why Docker `--device=/dev/dxg -v /usr/lib/wsl/lib/libdxcore.so:/usr/lib/libdxcore.so -v /opt/rocm/lib/libhsa-runtime64.so.1:/opt/rocm/lib/libhsa-runtime64.so.1` will enable (PyTorch in) ROCm in Docker in WSL. As a result, there is no driver running in WSL, which provides the files needed by Ollama.

There is a temporary but simple solution (I don't know when they will merge this):

* https://github.com/ollama/ollama/pull/6201

Just build and run it like this:

```bash
# clone
git clone https://github.com/evshiron/ollama
cd ollama
git checkout rocm-wsl-support

# build
go generate ./...
go build .

# when building is completed

# start service
./ollama serve

# start client
./ollama run phi3
```

**Comment by tcgu-amd** [comment]
Thank for chiming in @evshiron! @Henry715 I will be closing this ticket for now since there's no further actionable items. Please free free to post follow-up questions. Thanks!
