### ISSUE TITLE
ROCm (2.6?) Navi10 support on launch day?

### ISSUE THREAD

**Issue by oscarbg** [ROCm/ROCm#833]
Hi,
just asking if we can expect next ROCm release (2.6) on Navi launch day (7 july) or shortly after with support for 5700XT..
if not, some ETA?
thanks..

**Comment by gsedej** [comment]
Probably not, even as desktop cards aren't yet supported (linux 5.3) https://www.forbes.com/sites/jasonevangelho/2019/07/02/will-amd-radeon-rx-5700xt-graphics-cards-support-linux-gaming/#78381c9e3af9

**Comment by smartbitcoin** [comment]
Supporting Navi needs to update the llvm stack for gfx 10xx instruction set. it 's not trivial.  the LLVM upstream already done all the work and linux kernel 5.3 also have the patch ready for navi.   Rocm team just need to do all those integration and QA. it's sound will take a while.

But the customer's expectation is launch day support!!!

Intel will prepare linux kernel support few years ahead.
Nvidia never open source, but their proprietary driver never missing launch day. 

Amd is totally another story for linux,    launch day support always a dream for them as in general amd is a hardware company and honest speaking, their software team usually su.cks even improving recently. No blame,  we can just wait.  

One reason put rocm under opensource is one way they can mitigate their support pressure lol.

Even without ROCM stack , the pro driver 
https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-navi-linux
still failed majority opencl benchmark and performance bad ...

If there was a community around amd gpu application, could they complain?   at least I will.

**Comment by smartbitcoin** [comment]
apt update already found rocm 2.6 binary.  
update and have fun with navi lol.
amd yes !

**Comment by oscarbg** [comment]
@smartbitcoin nice find..
but no Navi signs on ROCM 2.6 right?
let's see for ROCM 2.7..

**Comment by JMadgwick** [comment]
According to AMD's website the 5700 XT has a little _less FP32 performance than Vega 56_. It's not a compute focused card and this is reflected in the architecture which was optimised for gaming. It wouldn't surprise me if it doesn't get added to ROCm, especially if it has performance problems.
Most likely it will be added but they will not be in a rush if it doesn't perform well and if it isn't going to be used in any pro cards that actually need ROCm.

**Comment by smartbitcoin** [comment]
does CUDA support all gpu or just gpu for data center ? 

does CUDA says that some main stream gpu need bullshit pci-e 3.0 atomic otherwise failed ?

why AMD discriminate their own gpu by gender ? 

why AMD says rocm is for computing so need pci-e 3.0 with atomic ? does CUDA not for computing?

why vega is biological son but vega M and all APU is bastard ?

I don't know if Lisa Su know all those complains.   But please no discrimination inside AMD , please treat all gpu equal.

**Comment by Degerz** [comment]
@smartbitcoin I mean it's pretty clear you don't know what you're talking about. PCIe atomics are [needed](https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/Installation_Guide/More-about-how-ROCm-uses-PCIe-Atomics.rst) because AMD requires a more powerful heterogeneous programming model in comparison to previous versions of CUDA or even current versions of CUDA on devices without NVLink support. Up [until](https://www.olcf.ornl.gov/wp-content/uploads/2018/02/SummitDev_Unified-Memory.pdf) Pascal's hardware support for unified memory, Nvidia had absolutely [no](https://stackoverflow.com/questions/23193151/atomic-operations-in-cuda-kernels-on-mapped-pinned-host-memory-to-do-or-not-to) way of supporting atomic operation in CUDA kernels on mapped pinned host memory ...

> But please no discrimination inside AMD , please treat all gpu equal. 

Then please learn to actually know what you're comparing ? Because programming on HIP/HCC is nothing like on common CUDA devices and is arguably closer to CUDA devices with NVLink support which were known to be thousands of dollars until just recently ...

**Comment by gsedej** [comment]
@smartbitcoin while i don't like your tone, your complaint about ROCm is somehow right.

I have old one laptop with geforce 9400m, and I can run (probably) any cuda app. I can also develop my cuda apps on the laptop and then deploy them to the datacenter.

Nvidia is much more popular and cuda is supported (probably) on an chip for at least 10 years. There are may "compute servers" at universities (e.g. basic xeon cpu + 4 titans) where students and researcher can run code. Cuda is being taught at UNIs 

With ROCm it's much different situation. You need to have quite recent dedicated card to even develop ROCm.
AMD idea of "datacenter" is probably different. Company buyes server from AMD with many Instinct cards and some desktop cards for specific task in mind.
Developers, who are trained to make ROCm app exactly for actual server at company. Just my understanding.

I think it would be right to make ROCm much more portable on all recent radeon HW and alto port it to windows. But I do understand that AMD simply doen't have enough manpower or resources.

And there is also technical limitation like atomics etc

**Comment by smartbitcoin** [comment]
@Degerz    gradually you will understand who don't know what they are talking about.

"Up until Pascal's hardware support for unified memory,"
check this out:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomic-functions
cuda atomic can apply on block share memory and device memory , system memory and unified memory ,  as you said until pascal ,   does pascal need pci-e 3.0 with atomic otherwise this function fail?

"more powerful heterogeneous programming model"
As opensource community, there always a philosophy,  "if you copy , please copy it better."  Rocm is 
 amd version of cuda which show up far more later. it migrate cuda to hip,  learned use LLVM to generate isa,  write a framework like hcc,   but does it better ? 

few fact:
1. Rocm kernel latency was much higher vs cuda kernel.  so higher latency means "powerful" ? 

2. Vega VII  have 1TB bandwidth in theory, but what's the real achievable in practice ,  please run rocm official https://github.com/RadeonOpenCompute/rocm_bandwidth_test,   what's the number you got ?  600GB is it right?   60% come from "more powerful model"?
2080ti only have 600GB bandwidth , please run their benchmark to check what's cuda can do.

3.  high cpu usage.
If you never really profile hcc, I show you example:
![image](https://user-images.githubusercontent.com/5984485/60969019-16c89c80-a2e4-11e9-8d91-ca0c1fb25819.png)
what it means?  ok ,  any software framework is for developer. if it frustrate developer,  it won't work.
If you start using rocm now , ( at least my first rocm is from 2015.),   lots of time , you need know something from kernel,  amdgpu, driver, hcc framework,  llvm compiler , ( actually, I not bad with all those .)  to fix some nasty bugs . don't tell me you never need fix bug and never meet nasty one.  eg the example one  screwed with hsa singal system.

Thanks for you explanation in your kindly reply , but it doesn't make sense for me as above reason.

**Comment by acowley** [comment]
A related notice from AMD about hardware support is the MIOpen 2.0 section of the ROCm 2.6 README: 

```
2.0 is the last release of active support for gfx803 architectures. In future releases, MIOpen will not actively debug and develop new features specifically for gfx803.
```

While I don’t think it’s fair to say much about Navi support given that they may well have just not finished it in time for the 2.6 release, I think it is clear based on the `hcc` deprecation, and end of debug support for gfx803 in MIOpen that AMD is taking measures to greatly limit the scope of their efforts.

I agree with the sentiment that CUDA’s broad compatibility and availability look tremendously good in contrast, but this is the reality of what AMD can do today.

**Comment by Degerz** [comment]
@smartbitcoin You still don't know what you're talking about ... 

And no Pascal doesn't support PCIe atomics, Nvidia uses another interconnect interface known as NVLink to support system-wide atomics. Pascal **needs** NVLink which is only available on select GPUs otherwise atomics within CUDA kernals between host/device and device memory isn't going to be visible as stated in the manual. 

> On GPU architectures with compute capability lower than 6.x, **atomics operations done from the GPU are atomic only with respect to that GPU**. If the GPU attempts an atomic operation to a peer GPU’s memory, the operation appears as a regular read followed by a write to the peer GPU, and the two operations are not done as one single atomic operation. Similarly, atomic operations from the GPU to CPU memory will not be atomic with respect to CPU initiated atomic operations.

This means that atomics are only coherent when executed from the **same** device or host.

As far as your philosophy is concerned, how on earth would that apply to ROCm if there's no open source CUDA runtime available to copy from ? 

ROCm may be flawed from a raw performance standpoint but it pioneered some of the features like unified memory first before CUDA even had the equivalent functionality ... 

Yes, it's sad that AMD is deprecating HCC and their support for gfx803 has fallen behind but this is why the project was open source to begin with so that **YOU**, the community can continue developing the kernel/runtime even if AMD decides to eventually ditch the project ...

**Comment by smartbitcoin** [comment]
@Degerz 
I feel so bad for you still don't understand why people complain about pci-e 3.0 atomic requirement for gfx803.

There are always different design and implementation for system wide atomic operation.  Nvidia have p2p lib,  later on with unified memory , NVLink etc and amd now have  Infinity Fabric Link after their first try to pci-e based atomic. 
But doesn't matter how the tech decision was made,   sacrifice huge user base to tiny features is not smart at all.

This is the blood difference betwen Nvidia and Amd.   Nvidia know how to put customer fist and win the love from developer , but on Amd side ... 

And now amd even deprecated gfx803 device but still make it not even bootable ( loading the driver and have xwindow works ) with pci-e 2.0 system.

I put so many question start with why , could you serious answer one?

why Pascal have atomic and still can run full cuda stack with "legacy" pci-e 2.0 system ?    why Fiji can't ?   just b/c you pick is pci-e 3 and frustrate the whole world?

Is that hard to have a simple failover to software and slow implementation to make the system at least bootable ?

**Comment by Degerz** [comment]
@smartbitcoin I do understand but ROCm has different design goals to CUDA so they aren't comparable ... 

ROCm is [intentionally](https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/Installation_Guide/More-about-how-ROCm-uses-PCIe-Atomics.rst) designed with heterogeneous programming in mind where interactions between host and device memory is seamless. Their design goals are not amendable to your constraints and while older systems without PCIe atomics can run on CUDA, you'll also have to live without heterogeneous memory model support too or face some really ugly workarounds which can be a maintenance burden or a performance degradation. **For AMD, heterogeneous memory isn't an option, it's a downright requirement ...** 

If you feel like you can do a better job than AMD can then feel free to contribute because it's open source after all ... 

IMO, AMD should drop every architecture except for gfx10 because their previous architectures now gets in the way HIP's goal of portability since they only support a wavefront size of 64 while Navi can support a wavefront size of 32 just like CUDA ... (can't get rid of the PTX asm or the libs but it's just one less problem to deal with)

**Comment by himanshugoel2797** [comment]
Hi,
I was wondering if there were any updates on ETA for Navi support?

**Comment by kentrussell** [comment]
As detailed at https://github.com/RadeonOpenCompute/ROCm/issues/887 , ROCm support is a bit of a complicated subject. Officially, it will be supported once we add it to the "Supported GPUs" list on the main README file. Look at the link above for a more detailed explanation of why this is what it is.

**Comment by nartmada** [comment]
Closing this ticket as it has became stale.  Sorry and unfortunately, Navi10 (gfx1010) is no longer supported in ROCm 6.0.0.

**Comment by cgmb** [comment]
For what it's worth, Navi 10 support is enabled in all ROCm packages provided by the OS itself on Debian 13 and Ubuntu 23.10. However, not all ROCm packages are available in this way, and none of them have been optimized for Navi 10 (so performance may be poor).
